# Generated by Django 4.2.5 on 2024-02-22 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('price', models.IntegerField()),
                ('is_exclusive', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='shoe_images/')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='e_commerce_app.brand')),
            ],
        ),
    ]
