# Generated by Django 4.2.5 on 2024-03-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0005_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(default=False),
            preserve_default=False,
        ),
    ]
