# Generated by Django 4.2.5 on 2024-03-10 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('e_commerce_app', '0007_order_order_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_value',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
